version: '3.8'

services:
  web:
    build:
      context: ./app
      dockerfile: Dockerfile.dev
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    env_file:
      - ./.env.dev
    depends_on:
      - db

  db:
    image: postgres:16.2
    volumes:
      - postgres_data:/var/lib/postgresql/data/
      - ./menu_database.sql:/docker-entrypoint-initdb.d/menu_database.sql
    env_file:
      - ./.env.dev
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    command: npm start
    ports:
      - "3000:3000"
    depends_on:
      - web

volumes:
  postgres_data:
  static_volume:
