version: '3.8'

services:
  web:
    build:
      context: ./app
      dockerfile: Dockerfile.prod
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8000
    expose:
      - 8000
    env_file:
      - ./.env.prod
    depends_on:
      - db

  db:
    image: postgres:16.2
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod


volumes:
  postgres_data:
  static_volume: